// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tunnel/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState represents the initial state of the blockchain.
type GenesisState struct {
	// params is all parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// tunnel_count is the number of tunnels.
	TunnelCount uint64 `protobuf:"varint,2,opt,name=tunnel_count,json=tunnelCount,proto3" json:"tunnel_count,omitempty"`
	// tunnels is the list of tunnels.
	Tunnels []Tunnel `protobuf:"bytes,3,rep,name=tunnels,proto3" json:"tunnels"`
	// latest_signal_prices_list is the list of latest signal prices.
	LatestSignalPricesList []LatestSignalPrices `protobuf:"bytes,4,rep,name=latest_signal_prices_list,json=latestSignalPricesList,proto3" json:"latest_signal_prices_list"`
	// total_fees is the type for the total fees collected by the tunnel
	TotalFees TotalFees `protobuf:"bytes,5,opt,name=total_fees,json=totalFees,proto3" json:"total_fees"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb87d9373a74da2e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTunnelCount() uint64 {
	if m != nil {
		return m.TunnelCount
	}
	return 0
}

func (m *GenesisState) GetTunnels() []Tunnel {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

func (m *GenesisState) GetLatestSignalPricesList() []LatestSignalPrices {
	if m != nil {
		return m.LatestSignalPricesList
	}
	return nil
}

func (m *GenesisState) GetTotalFees() TotalFees {
	if m != nil {
		return m.TotalFees
	}
	return TotalFees{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tunnel.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("tunnel/v1beta1/genesis.proto", fileDescriptor_cb87d9373a74da2e) }

var fileDescriptor_cb87d9373a74da2e = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0x02, 0x31,
	0x14, 0xc7, 0xef, 0x00, 0x31, 0x16, 0xe2, 0x70, 0x31, 0xe4, 0x40, 0x73, 0x22, 0x13, 0xd3, 0x35,
	0x88, 0x71, 0x74, 0xd0, 0x44, 0x63, 0xc2, 0x40, 0xc0, 0xc9, 0xe5, 0xd2, 0xab, 0xf5, 0x68, 0x52,
	0xda, 0x0b, 0x7d, 0x10, 0xfd, 0x16, 0x7e, 0x28, 0x07, 0x46, 0x46, 0x27, 0x63, 0xe0, 0x8b, 0x18,
	0xda, 0x4a, 0x22, 0xe8, 0x76, 0xef, 0xfd, 0x7f, 0xef, 0x77, 0xaf, 0x2d, 0x3a, 0x81, 0xa9, 0x94,
	0x4c, 0xe0, 0x59, 0x27, 0x65, 0x40, 0x3a, 0x38, 0x63, 0x92, 0x69, 0xae, 0xe3, 0x7c, 0xa2, 0x40,
	0x05, 0x87, 0x36, 0x8d, 0x5d, 0xda, 0x38, 0xca, 0x54, 0xa6, 0x4c, 0x84, 0xd7, 0x5f, 0x96, 0x6a,
	0x1c, 0x6f, 0x39, 0x72, 0x32, 0x21, 0x63, 0xfd, 0x4f, 0xe8, 0x8c, 0x26, 0x6c, 0xbd, 0x17, 0x50,
	0xf5, 0xce, 0xfe, 0x71, 0x08, 0x04, 0x58, 0x70, 0x81, 0xca, 0x76, 0x3a, 0xf4, 0x9b, 0x7e, 0xbb,
	0x72, 0x5e, 0x8b, 0x7f, 0x6f, 0x10, 0xf7, 0x4d, 0x7a, 0x5d, 0x9a, 0x7f, 0x9e, 0x7a, 0x03, 0xc7,
	0x06, 0x67, 0xa8, 0x6a, 0xb1, 0x84, 0xaa, 0xa9, 0x84, 0xb0, 0xd0, 0xf4, 0xdb, 0xa5, 0x41, 0xc5,
	0xf6, 0x6e, 0xd6, 0xad, 0xe0, 0x12, 0xed, 0xdb, 0x52, 0x87, 0xc5, 0x66, 0xf1, 0x2f, 0xf3, 0x83,
	0x29, 0x9d, 0xf9, 0x07, 0x0e, 0x28, 0xaa, 0x0b, 0x02, 0x4c, 0x43, 0xa2, 0x79, 0x26, 0x89, 0x48,
	0xf2, 0x09, 0xa7, 0x4c, 0x27, 0x82, 0x6b, 0x08, 0x4b, 0xc6, 0xd4, 0xda, 0x36, 0xf5, 0xcc, 0xc0,
	0xd0, 0xf0, 0x7d, 0x83, 0x3b, 0x6b, 0x4d, 0xec, 0x24, 0x3d, 0xae, 0x21, 0xb8, 0x42, 0x08, 0x14,
	0x10, 0x91, 0x3c, 0x33, 0xa6, 0xc3, 0x3d, 0x73, 0xf2, 0xfa, 0xce, 0x7e, 0x6b, 0xe2, 0x96, 0x6d,
	0x64, 0x07, 0xb0, 0x69, 0xdc, 0xcf, 0x97, 0x91, 0xbf, 0x58, 0x46, 0xfe, 0xd7, 0x32, 0xf2, 0xdf,
	0x56, 0x91, 0xb7, 0x58, 0x45, 0xde, 0xc7, 0x2a, 0xf2, 0x1e, 0x71, 0xc6, 0x61, 0x34, 0x4d, 0x63,
	0xaa, 0xc6, 0x38, 0x25, 0xf2, 0xc9, 0x5c, 0x3b, 0x55, 0x02, 0xd3, 0x11, 0xe1, 0x12, 0xcf, 0xba,
	0xf8, 0xc5, 0xbd, 0x08, 0x86, 0xd7, 0x9c, 0xe9, 0xb4, 0x6c, 0x88, 0xee, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x96, 0x1a, 0x25, 0x18, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalFees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.LatestSignalPricesList) > 0 {
		for iNdEx := len(m.LatestSignalPricesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LatestSignalPricesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Tunnels) > 0 {
		for iNdEx := len(m.Tunnels) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tunnels[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.TunnelCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TunnelCount))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.TunnelCount != 0 {
		n += 1 + sovGenesis(uint64(m.TunnelCount))
	}
	if len(m.Tunnels) > 0 {
		for _, e := range m.Tunnels {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LatestSignalPricesList) > 0 {
		for _, e := range m.LatestSignalPricesList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.TotalFees.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelCount", wireType)
			}
			m.TunnelCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TunnelCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tunnels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tunnels = append(m.Tunnels, Tunnel{})
			if err := m.Tunnels[len(m.Tunnels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestSignalPricesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestSignalPricesList = append(m.LatestSignalPricesList, LatestSignalPrices{})
			if err := m.LatestSignalPricesList[len(m.LatestSignalPricesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalFees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
