name: Tests
on: pull_request

jobs:
  chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Check go mod cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-chain-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-chain-

      - name: Run chain tests
        run: go test ./...
